### ISSUE TITLE
Using different scales in barplot simultaneously

### ISSUE THREAD

**Issue by LauraMCE** [LauraMCE/lncRNA_BC#10]
Hi! I'm here again with problems to construct graphs.

I have very different data of the expression of one particular lincRNA between breast cancer cell lines MCF-10A, MCF-7, BT474 and MDA-MB-231, as I show in my data Promlc [here](https://github.com/LauraMCE/lncRNA_BC/blob/master/Transcriptome/data/results/Promlc.csv)

I want to construct a barplot with these data, and I want it to look like this

![image](https://user-images.githubusercontent.com/53834929/65893511-ade64300-e36d-11e9-80fd-a7cce12ac343.png)

But... it looks like this...

![image](https://user-images.githubusercontent.com/53834929/65893682-f4d43880-e36d-11e9-8661-53c1fb75a4fb.png)

This is the R code that I've been following:

Pre-requisites:
```
library(plotrix)

plotrix::gap.barplot(Promlc, gap = c(150, 650), xaxlab= c("MCF-10A", "MCF-7", "BT474", "MDA-MB-231"), ytics = c( 50, 100, 800, 900), col =  c("blue", "light blue", "blue", "green"), ylim =c(0,400))
```

My principal problem is that I cannot stablish scales to make the barplot better. I'm not sure if I'm using the wrong tool, or I'm not providing the necessary parameters in my original code.

Please Help!!

**Comment by Duhyadi** [comment]
I think it will be necessary to add the `axis.break`. Maybe this [link](https://stackoverflow.com/questions/40206451/how-to-add-plot-to-gap-barplot-in-plotrix-package) can serve.

**Comment by almamelisa** [comment]
Hi Laura, 

This is solution, but in my computer I can´t put the white color for the gap

dat <- read.csv("Promlc.csv",header=T, check.names = FALSE)
dat
colnames(dat)<- c("Sample","Expression")
yticks<-c( 50, 100, 800, 900)
trans <- function(x){pmin(x,20) + 0.05*pmax(x-20,0)}
dat$Expression<-trans(dat$Expression)
ggplot(data=dat, aes(x=Sample, y=Expression)) +
  geom_col(position="dodge") +  geom_rect(aes(xmin=1, xmax=4, ymin=30, ymax=40, fill=rgb(1,1,1))) +
  scale_y_continuous (limits=c(0,NA),expand = c(0,0), breaks= trans(yticks), labels = yticks) +
  theme_classic()

**Comment by almamelisa** [comment]
Hi again @LauraMCE  and @Rodolfo47  

The script behind has missing one parenthesis, that's why the white "color" doesn't work. The secret to reorder is fix the arguments of the function trans with your data. 

So this script works, enjoy it!! 

`library(ggplot2)`

`dat <- read.csv("Promlc.csv",header=T, check.names = FALSE)`

`dat`

`samples<-c("MCF-10A", "MCF-7", "BT474", "MDA-MB-231")`

`dat<-data.frame(samples, dat$x)`

`colnames(dat)<- c("Sample","Expression")`

`dat`

`yticks<-c( 50, 100, 800, 900)`

`trans <- function(x){pmin(x,20) + 0.05*pmax(x-20,0)}`

`dat$Expression<-trans(dat$Expression)`

`ggplot(data=dat, aes(x=Sample, y=Expression, 
group=Sample, fill=Sample)) +
  geom_col(position="dodge") +  geom_rect(aes(xmin=1, xmax=4, ymin=30, ymax=40), fill="white") +
  scale_y_continuous (limits=c(0,NA),expand = c(0,0), breaks= trans(yticks), labels = yticks) +
  theme_classic()  `  

![image](https://user-images.githubusercontent.com/33968041/65926494-1576af80-e3bb-11e9-8749-3b4928db0f1b.png)

**Comment by Rodolfo47** [comment]
thank you for the update,
just I think you mean @necrosnake91

**Comment by almamelisa** [comment]
Yes, I mean @necrosnake91 
Thanks

**Comment by necrosnake91** [comment]
> Hi again @LauraMCE and @Rodolfo47
> 
> The script behind has missing one parenthesis, that's why the white "color" doesn't work. The secret to reorder is fix the arguments of the function trans with your data.
> 
> So this script works, enjoy it!!
> 
> `library(ggplot2)`
> 
> `dat <- read.csv("Promlc.csv",header=T, check.names = FALSE)`
> 
> `dat`
> 
> `samples<-c("MCF-10A", "MCF-7", "BT474", "MDA-MB-231")`
> 
> `dat<-data.frame(samples, dat$x)`
> 
> `colnames(dat)<- c("Sample","Expression")`
> 
> `dat`
> 
> `yticks<-c( 50, 100, 800, 900)`
> 
> `trans <- function(x){pmin(x,20) + 0.05*pmax(x-20,0)}`
> 
> `dat$Expression<-trans(dat$Expression)`
> 
> `ggplot(data=dat, aes(x=Sample, y=Expression, group=Sample, fill=Sample)) + geom_col(position="dodge") + geom_rect(aes(xmin=1, xmax=4, ymin=30, ymax=40), fill="white") + scale_y_continuous (limits=c(0,NA),expand = c(0,0), breaks= trans(yticks), labels = yticks) + theme_classic() `
> 
> ![image](https://user-images.githubusercontent.com/33968041/65926494-1576af80-e3bb-11e9-8749-3b4928db0f1b.png)

Hahahaha!! It's fine!! We were worried by the fact that ggplot (and R) had no idea about what it meant "white".

Thanks a lot @almamelisa !

**Comment by necrosnake91** [comment]
Hi Lau!

I leave you the code to (by using the cheat of merge two plots) cut the scale of your data in bar plot:

```
library(ggplot2)
require(gridExtra)
data <- read.csv("~/RNASeq/lncRNA_BC/Transcriptome/data/Promlc.csv", he=T)

x <- ggplot(data, aes(x=Sample))+
  geom_col(aes(y=Expression), fill=rgb(0,0.8,0.8))+
  coord_cartesian(ylim=c(-1, 100))+
  scale_y_continuous(breaks=c(0,90))

y <- ggplot(data, aes(x=Sample))+
  geom_col(aes(y=Expression), fill=rgb(0,0.8,0.8))+
  coord_cartesian(ylim=c(700, 850))+
  scale_y_continuous(breaks=c(750, 800))+
  theme(axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        legend.position = "none")+
  labs(y="")

Gx <- ggplotGrob(x)
Gy <- ggplotGrob(y)

grid.arrange(Gy, Gx)

```

See you next Wednesday!

**Comment by LauraMCE** [comment]
> > Hi again @LauraMCE and @Rodolfo47
> > The script behind has missing one parenthesis, that's why the white "color" doesn't work. The secret to reorder is fix the arguments of the function trans with your data.
> > So this script works, enjoy it!!
> > `library(ggplot2)`
> > `dat <- read.csv("Promlc.csv",header=T, check.names = FALSE)`
> > `dat`
> > `samples<-c("MCF-10A", "MCF-7", "BT474", "MDA-MB-231")`
> > `dat<-data.frame(samples, dat$x)`
> > `colnames(dat)<- c("Sample","Expression")`
> > `dat`
> > `yticks<-c( 50, 100, 800, 900)`
> > `trans <- function(x){pmin(x,20) + 0.05*pmax(x-20,0)}`
> > `dat$Expression<-trans(dat$Expression)`
> > `ggplot(data=dat, aes(x=Sample, y=Expression, group=Sample, fill=Sample)) + geom_col(position="dodge") + geom_rect(aes(xmin=1, xmax=4, ymin=30, ymax=40), fill="white") + scale_y_continuous (limits=c(0,NA),expand = c(0,0), breaks= trans(yticks), labels = yticks) + theme_classic() `
> > ![image](https://user-images.githubusercontent.com/33968041/65926494-1576af80-e3bb-11e9-8749-3b4928db0f1b.png)
> 
> Hahahaha!! It's fine!! We were worried by the fact that ggplot (and R) had no idea about what it meant "white".
> 
> Thanks a lot @almamelisa !

Hi! I'm so sorry. I forgot to close this issue. We did two barplots, but in one we did a trick (@necrosnake91 ) :) and in the other we don't, and this last one is the plot that @almamelisa helped us to construct. Thank you for your help!!!
