### ISSUE TITLE
Modify stadistic parameters to implement GSEA Analysis on DESEq results

### ISSUE THREAD

**Issue by LauraMCE** [LauraMCE/lncRNA_BC#15]
Hi! I have an issue that I want to discuss with you, hopping that you can give me an adecuate advice.

As you know, I want to know the lincRNA that are differentially expressed in resistant patients, and I also want to know more information about how this lincRNA are involved in resistant processes. To answer that, the simplest way is to look every lincRNA differentially expressed... but I have the problem that most of my differentially expressed lincRNA are only annotated and there is no functional or biological information about them. For that reason, I though it could be a good idea to perform a gene set enrichment analysis, to know in what kind of processes this lincRNA could be involved.

To do that, I was using SeqGSEA package in DE-only analysis mode in R, but when I'm running it, this appears...

```
Warning message:
In .local(object, ...) :
  in estimateDispersions: sharingMode=='gene-est-only' will cause inflated numbers of false positives unless you have many replicates.
```

Anyway, if I continue running the analysis, it stops in solving permutation and then appears this:

```
DEpermNBstat <- DENBStatPermut4GSEA(DEG, permuteMat)
There were 50 or more warnings (use warnings() to see the first 50)

```
And there is no object created.

In [here](https://github.com/LauraMCE/lncRNA_BC/blob/master/Transcriptome/data/results/tables/Data_1_Diff_genes.csv) you can find my count table for differential expression analysis. 

And in [here](https://github.com/LauraMCE/lncRNA_BC/blob/master/Transcriptome/bin/Choc_GSEA) is my script.

I want to know if you could help me with GSEA analysis: If you know another package in R for GSEA, or if you know how to avoid the replicates problem... or another way to perform this analysis.

Thanks!

**Comment by FernandaDiaz12** [comment]
##### Hi Laura.  
There are two problems with this issue: 

1. Your script runs with DeSEQ and your previous analyses run with DeSEQ two. So probably they won't be comparable. Check [this](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-014-0550-8) paper. 

2. If the problems are in the number of replicates. Then you have to change your "Metrics for Ranking Genes" and change it since for the default parameter  **Signal2Noise**  You must have at least three samples for each phenotype to use this metric.

Check the GSEA [documentation](https://software.broadinstitute.org/gsea/doc/GSEAUserGuideFrame.html).


###  :)

**Comment by LauraMCE** [comment]
> ##### Hi Laura.
> There are two problems with this issue:
> 
> 1. Your script runs with DeSEQ and your previous analyses run with DeSEQ two. So probably they won't be comparable. Check [this](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-014-0550-8) paper.
> 2. If the problems are in the number of replicates. Then you have to change your "Metrics for Ranking Genes" and change it since for the default parameter  **Signal2Noise**  You must have at least three samples for each phenotype to use this metric.
> 
> Check the GSEA [documentation](https://software.broadinstitute.org/gsea/doc/GSEAUserGuideFrame.html).
> 
> ### :)

Hi, @FernandaDiaz12 ! Thank you for the advice. I solved the problem of GSEA Analysis

First, I had to create my own GCT file with normalized counts of each sample and then specify the labels. I runned the GSEA Analysis with ranked option and it worked! The result looks like this:

![image](https://user-images.githubusercontent.com/53834929/69255606-bd1f8b00-0b7d-11ea-9e6b-e34018e01813.png)
 
Thank you so much!!!
