### ISSUE TITLE
Evaluation 30 October

### ISSUE THREAD

**Issue by camillethuyentruong** [LauraMCE/lncRNA_BC#16]
Hi Laura,

I had a look at your repo and README file. In general it is good and well-structured, well done! Below are some suggestions for improvement:

General README
- I suggest you include the information from Repo_analysis.md as an introduction for your project in the general README (or at least a link to Repo_analysis.md in the general README)
- Please describe shortly what are the files included in the STB folder, with links to your presentations

Exome project
The README file of the Exome project needs to be completed, explaining briefly the goals of the projects and describing the data, scripts and code for meta that are (or will be) included.

Transcriptome project:
- Please explain the code for the meta data in the README file
- The scripts Choc_GSEA and Choc_Volcano_plot are not described in the README file
- The folder for "results" is missing in data. I suggest you make a separate folder inside the Transcriptome directory for results and graphics

**Comment by LauraMCE** [comment]
> Hi Laura,
> 
> I had a look at your repo and README file. In general it is good and well-structured, well done! Below are some suggestions for improvement:
> 
> General README
> 
> * I suggest you include the information from Repo_analysis.md as an introduction for your project in the general README (or at least a link to Repo_analysis.md in the general README)
> * Please describe shortly what are the files included in the STB folder, with links to your presentations
> 
> Exome project
> The README file of the Exome project needs to be completed, explaining briefly the goals of the projects and describing the data, scripts and code for meta that are (or will be) included.
> 
> Transcriptome project:
> 
> * Please explain the code for the meta data in the README file
> * The scripts Choc_GSEA and Choc_Volcano_plot are not described in the README file
> * The folder for "results" is missing in data. I suggest you make a separate folder inside the Transcriptome directory for results and graphics

Thank you so much! I will work in the observations.

**Comment by LauraMCE** [comment]
> Hi Laura,
> 
> I had a look at your repo and README file. In general it is good and well-structured, well done! Below are some suggestions for improvement:
> 
> General README
> 
> * I suggest you include the information from Repo_analysis.md as an introduction for your project in the general README (or at least a link to Repo_analysis.md in the general README)
> * Please describe shortly what are the files included in the STB folder, with links to your presentations
> 
> Exome project
> The README file of the Exome project needs to be completed, explaining briefly the goals of the projects and describing the data, scripts and code for meta that are (or will be) included.
> 
> Transcriptome project:
> 
> * Please explain the code for the meta data in the README file
> * The scripts Choc_GSEA and Choc_Volcano_plot are not described in the README file
> * The folder for "results" is missing in data. I suggest you make a separate folder inside the Transcriptome directory for results and graphics

Hi! This observation is covered:
> * I suggest you include the information from Repo_analysis.md as an introduction for your project in the general README (or at least a link to Repo_analysis.md in the general README)

**Comment by LauraMCE** [comment]
> * Please describe shortly what are the files included in the STB folder, with links to your presentations

Done!

**Comment by LauraMCE** [comment]
> * The folder for "results" is missing in data. I suggest you make a separate folder inside the Transcriptome directory for results and graphics

Done!

**Comment by LauraMCE** [comment]
> * The scripts Choc_GSEA and Choc_Volcano_plot are not described in the README file

Done

**Comment by LauraMCE** [comment]
> * Please explain the code for the meta data in the README file

Done

**Comment by LauraMCE** [comment]
> Exome project
> The README file of the Exome project needs to be completed, explaining briefly the goals of the projects and describing the data, scripts and code for meta that are (or will be) included.

Done
