### ISSUE TITLE
Preliminary evaluation

### ISSUE THREAD

**Issue by Rodolfo47** [LauraMCE/lncRNA_BC#27]
Hi Laura,

In generar your repository structure are fine, and your general README.md are well documented an explicit. But it is necessary to use this 2 big sections? (Exoma and Transcriptoma) (is your decision) 

Your numerated scripts are well commented, but what about Choc_GSEA?
In your/Transcriptome/bin/ script 2 at line 25 and 34 you are using absolute paths, I suggest to use relative paths in order to avoid problems if the user do not set the /lncRNA_BC/ at ~/

You have no data or scripts in the /Exome/ directories, remember you must put your data in OSF or toy data (just like in the transcriptome section), and it looks like the .csv in bot meta directories are the same, is this correct?
Your Exome/README.md are empty
I understand this repo is in development, but this half is almost empty

Remember the evaluation [criteria](https://github.com/AliciaMstt/TallerBioinf/blob/master/Unidad4/Unidad4_proyectobioinf.md), at this moment you do not have any R plot and there are no discussion file

**Comment by LauraMCE** [comment]
> Hi Laura,
> 
> In generar your repository structure are fine, and your general README.md are well documented an explicit. But it is necessary to use this 2 big sections? (Exoma and Transcriptoma) (is your decision)
> 
> Your numerated scripts are well commented, but what about Choc_GSEA?
> In your/Transcriptome/bin/ script 2 at line 25 and 34 you are using absolute paths, I suggest to use relative paths in order to avoid problems if the user do not set the /lncRNA_BC/ at ~/
> 
> You have no data or scripts in the /Exome/ directories, remember you must put your data in OSF or toy data (just like in the transcriptome section), and it looks like the .csv in bot meta directories are the same, is this correct?
> Your Exome/README.md are empty
> I understand this repo is in development, but this half is almost empty
> 
> Remember the evaluation [criteria](https://github.com/AliciaMstt/TallerBioinf/blob/master/Unidad4/Unidad4_proyectobioinf.md), at this moment you do not have any R plot and there are no discussion file

Thanks!! I will work in my repo trying to solve this observations.

**Comment by LauraMCE** [comment]
> In generar your repository structure are fine, and your general README.md are well documented an explicit. But it is necessary to use this 2 big sections? (Exoma and Transcriptoma) (is your decision)

Yes, it is necessary because we can access to the information easier with this organization. Sometimes, clinical collaborations only need results from exome analysis, and, although we want to merge this information to complete molecular description of tumors, clinical projects are not likely to need transcriptomic results in our very particular case

**Comment by LauraMCE** [comment]
> Your numerated scripts are well commented, but what about Choc_GSEA?

Done

**Comment by LauraMCE** [comment]
> You have no data or scripts in the /Exome/ directories, remember you must put your data in OSF or toy data (just like in the transcriptome section), and it looks like the .csv in bot meta directories are the same, is this correct?

Almost done. Exome files will not be available because they were not obtained this semester (See Repo_Analysis.md for more details)

And yes, meta is the same because they are paired samples to analyze genomic and transcriptomic signatures.

**Comment by LauraMCE** [comment]
> In your/Transcriptome/bin/ script 2 at line 25 and 34 you are using absolute paths, I suggest to use relative paths in order to avoid problems if the user do not set the /lncRNA_BC/ at ~/

Done

**Comment by LauraMCE** [comment]
> You have no data or scripts in the /Exome/ directories, remember you must put your data in OSF or toy data (just like in the transcriptome section), and it looks like the .csv in bot meta directories are the same, is this correct?
> Your Exome/README.md are empty
> I understand this repo is in development, but this half is almost empty

I could not add toy data because I hadn't my files. It is explained in Repo_Analysis.md.

For anything else... almost done

**Comment by Rodolfo47** [comment]
Hi Laura,
I agree wit the Exoma and Transcriptoma structure
you commented the Choc_GSEA and fixed the paths in 2_COUNT_READS_TRANSCRIPTOME.R
you add the r plots
Your discussion file is well, just I suggest include the full references or links to the paper in the text citation
Well done!

**Comment by LauraMCE** [comment]
> Hi Laura,
> I agree wit the Exoma and Transcriptoma structure
> you commented the Choc_GSEA and fixed the paths in 2_COUNT_READS_TRANSCRIPTOME.R
> you add the r plots
> Your discussion file is well, just I suggest include the full references or links to the paper in the text citation
> Well done!

Thanks!! I didn't add the references!! I didn't notice that, sorry. I'll fix it immediately. Thank you!!
