### ISSUE TITLE
Troubles with sublisting in Markdown

### ISSUE THREAD

**Issue by LauraMCE** [LauraMCE/lncRNA_BC#9]
Hi! I was trying to put in order my repo and I started with my [README](https://github.com/LauraMCE/lncRNA_BC/blob/master/README.md). 

I organized my repo with the following folders:
1. Transcriptome
- Bin
- Graphs
- Metadata
- Data

2. Exome
- Bin
- Metadata
- Data

And, for specific use in my project, I need to have sub-folders in Data, just like this:

- Data
    - Results
        - Quality (for FastQC reports)
        - Tables (for the count tables)
        - DESeq objects (for DESeq objects, because it contains inside a lot of factor's info)

But I couldn't achieved that... All my folders look like they were located in the same level in my organization, just like [this](https://github.com/LauraMCE/lncRNA_BC/blob/master/README.md). I tried also to use numbered list style, but it doesn't help to follow the README...

Could you help me with that?

**Comment by necrosnake91** [comment]
Hi, Lau!

You could try to insert the code in the same row of your list. Then, press enter and tab to include the next level, something like this:

1. Number one 
2. Number two ```code```
     - sublevel of number two

Hope this works!

Cheers!

**Comment by LauraMCE** [comment]
Thanks @necrosnake91 and everybody!! The README looks pretty good now! It worked!
